### ISSUE TITLE
"Civilian/Non-Civilian" graph in "Reporting" section doesn't reproduce actual data

### ISSUE THREAD

**Issue by florianap** [equalitie/open-corroborator#28] opened 2016-03-17 14:11 UTC
*\* tested with Iceweasel 38.7.0 on Debian 8, Firefox 45.0 on Fedora 23, Chromium 49.0.2623.87 on Debian 8.3 (64-bit) **
### Reproduction steps
1. Click on "Reporting" in the top menu of the CUI.
2. Click on "Actors".
3. Select "Civilian/Non-Civilian" in the "Actors by" drop-down menu.
### Expected results

A graph on actual ratio between civilian and non-civilian actors should appear.
### Actual results

The graph results in a 100% non-civilians although there are several actors labeled as "Civilian".

![reporting_actorsciv](https://cloud.githubusercontent.com/assets/9517238/13848508/7a14772e-ec52-11e5-9bf7-29f0f2280a7c.png)
### Note

When creating an actor from CUI, actors are civilian by default.
The admin interface does not record that these actors are civilian, and the box "Civilian" in the admin panel ( https://demo2.corroborator.org/admin/corroborator_app/actor/5/ ) remains blank (see screenshot). 

![admin_edit_actor](https://cloud.githubusercontent.com/assets/9517238/13848503/6c312d32-ec52-11e5-851b-0d1f9f3c46c9.png)

**Comment by graphiclunarkid** [comment] 2016-04-06 15:41
@kromcuich couldn't reproduce this one. @ggaughan, if you can reproduce this, please comment with the likely impact and the size of effort needed to fix it. We will then decide where to put it in the backlog order. If you can't reproduce it either then we should close it and wait to see if a customer finds it in the wild.

**Comment by ggaughan** [comment] 2016-04-07 13:41
"When creating an actor from CUI, actors are civilian by default" - this doesn't appear to be the case. The dropdowns for Sex, Child/Adult, Civilian/Non-Civilian have a heading which gives the impression that there is a default  for the Civilian option but there is no default. This explains the graph and the admin issue.

Perhaps the dropdown-heading translations could be changed to say 'Please choose' or something to make it less misleading.

**Closed as completed** 2016-05-02 13:58 UTC
Labels: enhancement
